import React from 'react'

import { cn } from "@/lib/utils"
import { Slider } from "@/components/ui/slider"

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
 

 
type SliderProps = React.ComponentProps<typeof Slider>
 
export function SliderDemo({ className, ...props }: SliderProps) {
  return (
    <Slider
      defaultValue={[50]}
      max={100}
      step={1}
      className={cn("w-[60%]", className)}
      {...props}
    />
  )
}


export default function Questions() {


  return (
    <div   style={{
      width: '100%',
      boxSizing: 'border-box',
      height: "100%",
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      padding: '3rem 2rem',
    }}>
      <div style={{
        fontSize: '1.2rem',
        fontWeight: 'bold',

      }}>Questions & Answers</div>

    <div style={{
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      boxSizing: 'border-box',
      paddingBottom: "0rem",
      height: "100%",
      overflow: 'auto',
      width: "100%"
    }} className="scrollbar">
      <Accordion type="single" collapsible className="w-full">
        <AccordionItem value="item-1" className="border-whispyblue/10">
          <AccordionTrigger>Why Checklists?</AccordionTrigger>
          <AccordionContent>
            <div style={{
              padding: '1rem 0',
            }}>
          Checklists have saved lives in the medical industry.  However they have many other benefits.  For instance, planning complex procedures, providing a template for automating procedures, context switching between tasks, as well as a store of shared knowledge.
            </div>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-2" className="border-whispyblue/10">
          <AccordionTrigger>Do new things right the first time</AccordionTrigger>
          <AccordionContent>
            <div style={{
              padding: '1rem 0',
            }}>
            With a repository of checklists created by users who know the domain, or checklists generated by AI, you can have greater confidence that you're not leaving something out when planning important tasks.  

            </div>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-3" className="border-whispyblue/10">
          <AccordionTrigger>Focus</AccordionTrigger>
          <AccordionContent>
            <div style={{
              padding: '1rem 0',
            }}>
              From the comfort of your phone you can plan your tasks.  When it's time to execute, you can step through each task.  Need to switch tasks?  All the information will be right there when you need to switch back. 

            </div>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-3" className="border-whispyblue/10">
          <AccordionTrigger>Group Planning</AccordionTrigger>
          <AccordionContent>
            <div style={{
              padding: '1rem 0',
            }}>
              Make sure everyone is on the same page by communicating with precision.  

            </div>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-4" className="border-whispyblue/10">
          <AccordionTrigger>Analysis</AccordionTrigger>
          <AccordionContent>
            <div style={{
              padding: '1rem 0',
            }}>
            Make sure that your manual processes make sense and achieve the desired result. Easily generate dozens of variations of expected budgets, expected task assignments and schedules etc. to envision how your plans will play out
            </div>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-4" className="border-whispyblue/10">
          <AccordionTrigger>Versioned Manual Processes</AccordionTrigger>
          <AccordionContent>
            <div style={{
              padding: '1rem 0',
            }}>
    
            By putting them down into systematic checklists, manual processes can be tested and refactored just like software.  This can allow for continuous improvement and cutting out unnecessary red tape while still minimizing negative tradeoffs.

            </div>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-5" className="border-whispyblue/10">
          <AccordionTrigger>Progressively Automate your tasks</AccordionTrigger>
          <AccordionContent>
            <div style={{
                padding: '1rem 0',
              }}>
              If you find one step of your checklist can be automated, easily integrate it into your existing manual process.  Don't worry about spinning up a cloud service yourself just to run a little script.
            </div>
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-5" className="border-whispyblue/10">
          <AccordionTrigger>No Code Backend</AccordionTrigger>
          <AccordionContent>
            <div style={{
                padding: '1rem 0',
              }}>
              Orchestrating highly asynchronous tasks, you can integrate information from various API's and send it wherever it needs to go.  But you don't need a backend coder to do it, you can create a workflow from your phone.
            </div>
          </AccordionContent>
        </AccordionItem>
      </Accordion>

    </div>

    </div>
  )
}

